server:
  port: 9999
  compression:
    enabled: true
    mime-types: application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain
    min-response-size: 1024
  servlet:
    session:
      timeout: 1800
  web:
    resources:
      chain:
        cache: false

spring:
  profiles.active: dev
  freemarker:
    checkTemplateLocation: false

  #  mongodb配置
  data.mongodb.uri: mongodb://10.0.11.50:27017/ai

  #  i18n资源文件配置
  messages:
    basename: i18n/base/messages,i18n/main/messages,i18n/mongodb/messages
    encoding: UTF-8
    cache-duration: -1

  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15

    #mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.11.21:33067/RVM3_TEST?characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8&generateSimpleParameterMetadata=true
    username: root
    password: root

  #  jdbcTemplate配置
  jdbc:
    template:
      fetch-size: -1
      max-rows: -1
      query-timeout:
  servlet:
    multipart:
      max-file-size: 100MB
springdoc:
  packages-to-scan:
    - com.bcd
  swagger-ui:
    path: /swagger-ui.html


hbase:
  zookeeper:
    quorum: 10.0.11.34,10.0.11.33,10.0.11.38
    property:
      clientPort: 2181

workPoolSize: 10
alarmTimeOffset: 60

alarmSourcePath: alarm.txt
signalSourcePath: signal.txt
gb_signalSourcePath: signal_gb.txt
vehicleInfoPath: /Users/baichangda/Downloads/vehicleInfo.xlsx
vehicleInfoPwd: bwwbn@rvm

tableReplace: saic:json_09m,saic:json_recover